title: "Wind Energy Insights"
description: "Comprehensive insights on wind energy..."
theme: jekyll-theme-modernist  # Uncomment this
baseurl: ""
url: "https://elphan45.github.io"
lang: de

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

future: false
include:
  - _posts

plugins:
  - jekyll-seo-tag

# Modernist theme needs this empty section
modernist:
  # Custom variables can go here