title: "Wind Energy Insights"
description: "Comprehensive insights on wind energy..."
theme: jekyll-theme-modernist  
baseurl: "/Wind-Load_Insights"         # <-- Baseurl
url: "https://elphan45.github.io"      # <-- Main URL
lang: de

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

include:
  - _posts

plugins:
  - jekyll-seo-tag

# Modernist theme needs this empty section
modernist:
  # Custom variables can go here

# Post settings
permalink: /posts/:title/
future: true  # Set to true to display future-dated posts

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
