title: Filderstadt Chronicles
description: Historical and Cultural Chronicles of Filderstadt
theme: jekyll-theme-minimal
baseurl: "/filderstadt.github.io"
url: "https://elphan45.github.io"
markdown: kramdown
future: false
