remote_theme: jekyll-theme-tufte
title: Filderstadt Chronicles
author: Your Name
description: "Historical and Cultural Chronicles of Filderstadt"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

# LaTeX-style settings
scholar:
  style: apa
  locale: de
  sort_by: author
  source: ./_bibliography
  bibliography: references.bib
